import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f6f7f8" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.015,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  backBtn:   { padding: 4 },
  searchBtn: { padding: 4 },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: width * 0.045,
    fontWeight: "700",
    color: "#0f172a",
  },
  list: { padding: width * 0.04, paddingBottom: height * 0.1 },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: width * 0.035,
    borderRadius: 12,
    marginBottom: height * 0.012,
    elevation: 1,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  avatar: {
    width: width * 0.12,
    height: width * 0.12,
    borderRadius: width * 0.06,
    marginRight: width * 0.03,
  },
  info: { flex: 1 },
  name: { fontSize: width * 0.04, fontWeight: "600", color: "#0f172a" },
  code: { fontSize: width * 0.032, color: "#64748b", marginTop: 2 },
  right: { flexDirection: "row", alignItems: "center", gap: 10 },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  badgeActive:       { backgroundColor: "#e6f2ff" },
  badgeInactive:     { backgroundColor: "#e2e8f0" },
  badgeText:         { fontSize: width * 0.03, fontWeight: "600" },
  badgeTextActive:   { color: "#137fec" },
  badgeTextInactive: { color: "#475569" },
  fab: {
    position: "absolute",
    bottom: height * 0.03,
    right: width * 0.06,
    width: width * 0.14,
    height: width * 0.14,
    borderRadius: width * 0.07,
    backgroundColor: "#137fec",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
  },
});
